// Generated by purs bundle 0.14.4
var PS = {};
(function(exports) {
  "use strict";

  exports.log = function (s) {
    return function () {
      console.log(s);
    };
  };
})(PS["Effect.Console"] = PS["Effect.Console"] || {});
(function($PS) {
  // Generated by purs version 0.14.4
  "use strict";
  $PS["Effect.Console"] = $PS["Effect.Console"] || {};
  var exports = $PS["Effect.Console"];
  var $foreign = $PS["Effect.Console"];
  exports["log"] = $foreign.log;
})(PS);
(function($PS) {
  // Generated by purs version 0.14.4
  "use strict";
  $PS["Step0"] = $PS["Step0"] || {};
  var exports = $PS["Step0"];
  var Effect_Console = $PS["Effect.Console"];                
  var main = Effect_Console.log("yolo");
  exports["main"] = main;
})(PS);
PS["Step0"].main();